services:
  php:
    profiles: ["prod"]
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html
    networks:
      - internal
  nginx:
    profiles: ["prod"]
    build: ./docker/nginx
    ports:
      - 8008:80
    networks:
      - internal
  db:
    profiles: ["prod", "dev"]
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1488
    networks:
      - internal
  adminer:
    profiles: ["dev"]
    image: adminer
    restart: always
    ports:
      - 7777:8080
    networks:
      - internal
  # DEV DEV DEV DEV  DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV
  node:
    profiles: ["dev"]
    build: ./docker/node
    volumes:
      - ./frontend:/var/www/html
      - ./docker/node:/scripts
    ports:
      - 3000:3000
    networks:
      - internal
  symfony:
    profiles: ["dev"]
    build: ./docker/symfony
    #tty: true
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    networks:
      - internal
networks:
  internal:
    driver: bridge
