services:
  php:
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html
    networks:
      - internal
  nginx:
    build: ./docker/nginx
    ports:
      - 8008:80
    networks:
      - internal
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      #POSTGRES_DB: value
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1488
    #volumes:     
    #  - ./docker/db:/var/lib/postgresql/data
    networks:
      - internal
  adminer:  
    image: adminer
    restart: always
    ports:
      - 7777:8080
    networks:
      - internal
  # DEV DEV DEV DEV  DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV DEV
  node:
    build: ./docker/node
    #tty: true
    volumes:
      - ./frontend:/var/www/html
      - ./docker/node:/scripts
    ports:
      - 3000:3000
  symfony:
    build: ./docker/symfony
    tty: true
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
networks:
  internal:
    driver: bridge
